### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by mf85** [zemasoft/eset-challenge-evm2#2] opened 2018-11-26 09:36 UTC
Hey,
When I run the attached program , virtual machine crashes.

Out of curiosity, did you send it to ESET or are you planning to?

[crash.zip](https://github.com/zemasoft/eset-challenge-evm2/files/2614806/crash.zip)

**Comment by zemasoft** [comment] 2018-11-26 10:38
Hi,

You are right, division by zero is not handled. Since there is not defined an expected behavior when dividing by zero, I will fix it simply by throwing some runtime exception. Thank you for reporting this.

No I haven't sent it to ESET yet and I am not sure whether I will. Should I? :-) Primarily, I was having fun working on the task...

**Comment by zemasoft** [comment] 2018-11-26 12:12
Fixed with [2046ac](https://github.com/zemasoft/eset-challenge-evm2/commit/2046acee863326db1e79544ef9b568acb58cfb2f).

**Closed by zemasoft** 2018-11-26 12:12 UTC

**Comment by mf85** [comment] 2018-11-26 12:45
Tested. It works!
gj ;-)

Yeah exactly, I also had a lot of fun coding this task. 

"Should I?"
Well, the task is meant for Poland, so assuming you dont want to move to Poland , send it only if you are 
interested in their opinion. My solution is almost a year old, haven't sent it either. 
Don't know why but these very hi-tech companies are a bit intimidating.

Anyway, gl and hf with whatever you are currently doing.
